### ISSUE TITLE
isReactionaryBot provides stats for self

### ISSUE THREAD

**Issue by dperny** [Wyboth/isReactionaryBot#5]
re: https://www.reddit.com/r/FULLCOMMUNISM/comments/3c3zzz/isreactionarybot_has_been_shadowbanned/css4c05

The problem is that the new username parsing function doesn't return the username as all lowers, like I think I did before. I'll do a PR later today or tomorrow that lowercases the username before it returns.

**Comment by Wyboth** [comment]
Alright, I'll expect it. Thanks for letting me know.

**Comment by Wyboth** [comment]
I hope you are okay with me doing this, but I believe I solved it. All I did was change `return match.group('username')` to `return match.group('username').lower()`. If that isn't right, I'll revert it and let you do it, but it seemed to be correct.

**Comment by dperny** [comment]
No, that's actually exactly what I was gonna do anyway, I just haven't
gotten to my coding computer yet.

**Comment by Wyboth** [comment]
Great, I'll close this issue.
